[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig = True
WarnOnInvalidTags = True
ClearInvalidTags = False
AllowEditorTagUnloading = True
AllowGameTagUnloading = False
FastReplication = False
bDynamicReplication = False
InvalidTagCharacters = "\"\',"
NumBitsForContainerSize = 6
NetIndexFirstBitSegment = 16

+GameplayTagList = (Tag="SFX.UI.MainMenu.Buttons.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.MainMenu.Buttons.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.LevelChoosingMenu.Buttons.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.LevelChoosingMenu.Buttons.Clicked",DevComment="")

;+GameplayTagList = (Tag="SFX.UI.Button.PauseGame.Hovered",DevComment="Use SFX.PauseGame as SFX.UI.Button.PauseGame.Clicked")
+GameplayTagList = (Tag="SFX.UI.Button.EndTurn.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.EndTurn.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Building.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Building.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.MoveBuilding.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.MoveBuilding.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.DemolishBuilding.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.DemolishBuilding.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.BuildingCategory.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.BuildingCategory.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.NextWaveInfo.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.NextWaveInfo.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Time.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Time.Clicked",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Time.Pause.Hovered",DevComment="")
+GameplayTagList = (Tag="SFX.UI.Button.Time.Pause.Clicked",DevComment="")

+GameplayTagList = (Tag="SFX.PauseGame",DevComment="")
+GameplayTagList = (Tag="SFX.ResumeGame",DevComment="")

+GameplayTagList = (Tag="SFX.Resources.Default.Awarded",DevComment="")
+GameplayTagList = (Tag="SFX.Resources.Gold.Awarded",DevComment="")
+GameplayTagList = (Tag="SFX.Resources.Food.Awarded",DevComment="")
+GameplayTagList = (Tag="SFX.Resources.Population.Awarded",DevComment="")

+GameplayTagList = (Tag="SFX.GamePhase.StartGame",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.LoseGame",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.WinGame",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.Building.Start",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.Combat.Start",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.Combat.Win",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.Reward.Start",DevComment="")
+GameplayTagList = (Tag="SFX.GamePhase.Reward.End",DevComment="")

+GameplayTagList = (Tag="SFX.Building.Default.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Placed.Success",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Placed.Restricted",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Demolished",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Resurrected",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Building.Default.TakeDamage",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Default.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Default.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Default.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Default.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Default.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Default.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wolf-goblin.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Chihua-goblin.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Dog-ogr.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Don.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Don.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Don.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Don.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Don.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Don.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Wizard.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wizard.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wizard.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wizard.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wizard.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Wizard.SpawnUnit",DevComment="")

+GameplayTagList = (Tag="SFX.Unit.Flying.Selected",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Flying.Spawn",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Flying.Death",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Flying.Attack",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Flying.TakeDamage",DevComment="")
+GameplayTagList = (Tag="SFX.Unit.Flying.SpawnUnit",DevComment="")
