;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="SFX.Unit.Wolf.TakeDamage",NewTagName="SFX.Unit.Orc.TakeDamage")
+GameplayTagRedirects=(OldTagName="SFX.Unit.Wolf",NewTagName="SFX.Unit.Orc")
+GameplayTagList=(Tag="SFX.Building.Default.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Death",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Demolished",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Placed.Restricted",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Placed.Success",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Resurrected",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.Selected",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Default.TakeDamage",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Mortar.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Building.Wood.Damage",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.Building.Start",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.Combat.Start",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.Combat.Win",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.LoseGame",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.Reward.End",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.Reward.Start",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.StartGame",DevComment="")
+GameplayTagList=(Tag="SFX.GamePhase.WinGame",DevComment="")
+GameplayTagList=(Tag="SFX.PauseGame",DevComment="")
+GameplayTagList=(Tag="SFX.Resources.Food.Awarded",DevComment="")
+GameplayTagList=(Tag="SFX.Resources.Gold.Awarded",DevComment="")
+GameplayTagList=(Tag="SFX.Resources.Population.Awarded",DevComment="")
+GameplayTagList=(Tag="SFX.ResumeGame",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Building.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Building.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Building.Unaffordable.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Building.Unaffordable.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.BuildingCategory.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.BuildingCategory.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.DemolishBuilding.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.DemolishBuilding.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.EndTurn.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.EndTurn.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.MoveBuilding.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.MoveBuilding.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.NextWaveInfo.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.NextWaveInfo.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Time.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Time.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Time.Pause.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.Time.Pause.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.ToggleCardBook.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Button.ToggleCardBook.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.Grid.Cell.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.LevelChoosingMenu.Buttons.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.LevelChoosingMenu.Buttons.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.UI.MainMenu.Buttons.Clicked",DevComment="")
+GameplayTagList=(Tag="SFX.UI.MainMenu.Buttons.Hovered",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Chihuahua.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.Death",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.Selected",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.Spawn",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.SpawnAbility",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Default.TakeDamage",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Dobermag.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Dobermag.TakeDamage",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Duck.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Duck.TakeDamage",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.FlyingPug.Attack",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Goblin.TakeDamage",DevComment="")
+GameplayTagList=(Tag="SFX.Unit.Orc.TakeDamage",DevComment="")

