// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

#include "CoreMinimal.h"

/** (Gregory-hub) */
namespace AudioTags
{
    // ── UI ── MainMenu ────────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_MAINMENU_BUTTONS_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_MAINMENU_BUTTONS_CLICKED)

    // ── UI ── LevelChoosingMenu ───────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_LEVELCHOOSINGMENU_BUTTONS_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_LEVELCHOOSINGMENU_BUTTONS_CLICKED)

    // ── UI ── Buttons ─────────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_ENDTURN_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_ENDTURN_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDING_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDING_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDING_UNAFFORDABLE_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDING_UNAFFORDABLE_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_MOVEBUILDING_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_MOVEBUILDING_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_DEMOLISHBUILDING_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_DEMOLISHBUILDING_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDINGCATEGORY_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_BUILDINGCATEGORY_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_NEXTWAVEINFO_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_NEXTWAVEINFO_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TOGGLECARDBOOK_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TOGGLECARDBOOK_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TIME_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TIME_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TIME_PAUSE_HOVERED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_BUTTON_TIME_PAUSE_CLICKED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UI_GRID_CELL_HOVERED)

    // ── Pause game ────────────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_PAUSEGAME)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_RESUMEGAME)

    // ── Resources ─────────────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_RESOURCES_GOLD_AWARDED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_RESOURCES_FOOD_AWARDED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_RESOURCES_POPULATION_AWARDED)

    // ── GamePhase ─────────────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_STARTGAME)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_LOSEGAME)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_WINGAME)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_BUILDING_START)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_COMBAT_START)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_COMBAT_WIN)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_REWARD_START)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_GAMEPHASE_REWARD_END)

    // ── Building - Default ────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_SELECTED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_PLACED_SUCCESS)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_PLACED_RESTRICTED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_DEMOLISHED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_DEATH)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_RESURRECTED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_ATTACK)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_BUILDING_DEFAULT_TAKEDAMAGE)

    // ── Unit ── Default ───────────────────────────────────────────────────────
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_SELECTED)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_SPAWN)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_DEATH)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_ATTACK)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_TAKEDAMAGE)
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(SFX_UNIT_DEFAULT_SPAWNABILITY)
} // namespace AudioTags
